### ISSUE TITLE
Allow download of attached files/media using API Token

### ISSUE THREAD

**Issue by viniciuscb** [thecartercenter/nemo#669]
When we get a results list from an API call we do not have the link to the attached files. Also, the attached files/media of the responses can only be downloaded today if the user is logged in.

Our proposal is to allow download of media files using the API token (use the route media/objects#show).

**Comment by cooperka** [comment]
Hi @viniciuscb, similar to #671, have you tried our new OData API for this feature?

**Comment by cooperka** [comment]
If the new API doesn't meet your need please do reply here.
