### ISSUE TITLE
Calculation of two variables.

### ISSUE THREAD

**Issue by gichia300** [thecartercenter/nemo#700]
Is it possible to divide two variables?

**Comment by smoyth** [comment]
Hi @gichia300. Yes, that's possible if you're using ODK Collect. See the `Default Answer` field in when editing a question. You would enter something like `calc($MyQuestion / $MyOtherQuestion)`.

It's not currently possible with the web client or SMS client.

**Comment by gichia300** [comment]
Actually that didn't work for me, I had to use XPath format calc($MyQuestion div ($MyOtherQuestion))

**Comment by smoyth** [comment]
Wow look at that! I had no idea `div` was division in XPath. Thanks!
