### ISSUE TITLE
Error: Operations are currently not running. 

### ISSUE THREAD

**Issue by glorykakessa** [thecartercenter/nemo#769]
When users are trying to export data using the export to CVS Format tool they receive this message "Error: Operations are currently not running. Please contact administrator"

I want to know how to fix this problem? Is there an activation or deactivation functionality?

**Comment by glorykakessa** [comment]
The System Version is 9.20

**Comment by cooperka** [comment]
Hi @glorykakessa, "operations are currently not running" generally means the Delayed Job service on your linux server is not running. Can you try `sudo systemctl restart delayed-job` and see if that helps?

Happy to diagnose further depending on how that goes -- the next thing I'd need to know is the output of `sudo systemctl status delayed-job`.

**Comment by glorykakessa** [comment]
Hi @cooperka i've tried to restart the dealayed-job but it didn't work, the after i decided stop all and restart later using the following steps : 

I've first stoped the delayed-job and the nginx server as well with this command `sudo systemctl stop delayed-job && sudo systemctl stop nginx` 

I've wait some minute and I've restart again using this `sudo systemctl restart delayed-job && sudo systemctl restart nginx`

And everything went well!!

**Comment by cooperka** [comment]
Fabulous! I'm glad it's working, let us know if we can help with anything else.
