### ISSUE TITLE
(Question) Are y'all okay with PRs for appeasing Brakeman?

### ISSUE THREAD

**Issue by bananabrann** [thecartercenter/nemo#887]
If I manage to fix something that addresses a legit vulnerability or appeases Brakeman, would y'all be willing to review the PR and merge it in, i.e. would it fit into any release schedules?

I'm not *too* familiar with Rails apps, so no guarantees!

**Comment by cooperka** [comment]
Sure! We don't have a lot of spare time for this, but if you submit small, well-documented PRs I am happy to accept them. Thank you.
