### ISSUE TITLE
ODK Collect SSL connection?

### ISSUE THREAD

**Issue by poVoq** [thecartercenter/nemo#905]
Looking at the .env file for production mode it seems like by default ODK Collect connects unencrypted http via port 8443?

Is there a way to configure that more securely?

Thanks for the help!

**Comment by cooperka** [comment]
yes, you should set all of those values (including http and www.example.com) in `.env.production` to match your own server; normally a website would default to using port 443 for secure HTTPS connections, in case that helps.

**Comment by poVoq** [comment]
So this is not a direct connection that only ODK Collect uses? So I can just set it to my normal domain name with "https" and port 443 and everything goes through Nginx (which handles the SSL certificate)? Why mention ODK Collect specifically then?

**Comment by cooperka** [comment]
Collect can connect to any website on any port, it just uses whatever you specify in your Collect settings. The NEMO docs mention Collect there specifically because in development it's useful to intentionally use an insecure port for local server debugging:

> We default to a port of 8443 in development because ODK Collect can connect to that port over http **without complaining about security.** [but it can connect to any port, and generally requires the connection to be secure HTTPS except for on port 8443].

**Comment by cooperka** [comment]
Updated docs on main branch! Thanks for the question.
